############################################
#          DO NOT TOUCH THIS FILE          #
############################################

version: 0.2

phases:
  build:
    commands:
      - docker build -t gcr.io/lhgames-2017/enter_team_name_here .
  post_build:
    commands:
      - docker push gcr.io/lhgames-2017/enter_team_name_here
